# Qwen API Token Groups Configuration
# 支持多个账号轮询，防止单账号被封

# Token 组配置（必填）
# 每组必须包含 token 字段
qwen_token_groups:
  - token: "your_jwt_token_1"
  - token: "your_jwt_token_2"

# API配置
qwen_api_base_url: "https://chat.qwen.ai/api/v2"

# 支持的模型列表
# - qwen3-235b-a22b
# - qwen3-coder-plus
# - qwen3-coder-30b-a3b-instruct

# 通用配置
port: 8220
qwen_source: "web"
qwen_timezone: "Asia/Shanghai"
log_level: "INFO"
log_file: "logs/qwen_api.log"
config_file: "config.yaml"
